### ISSUE TITLE
Tkinter error in setup

### ISSUE THREAD

**Issue by diegocepedaw** [skolchin/gbr#1]
I am trying to set up this project on Python 3.7, ubuntu 20.04.1 LTS. When I run gbr2.py I get the following error 
`Traceback (most recent call last):
  File "gbr2.py", line 1301, in <module>
    main()
  File "gbr2.py", line 1294, in main
    window = GbrGUI2()
  File "gbr2.py", line 932, in __init__
    tk.Tk.__init__(self, "Go board")
  File "/usr/lib/python3.8/tkinter/__init__.py", line 2261, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
_tkinter.TclError: couldn't connect to display "Go board"`

Do you know what the issue could be?

**Comment by skolchin** [comment]
I have never tested this in Unix, sorry. I guess this is some kind of Tkinter internals, at least quick google search return this:
https://stackoverflow.com/questions/59006466/local-machine-tkinter-tclerror-couldnt-connect-to-display-0
Hope it would help
